<section id="days-container">

    <h3 class="h3-titles">
        <span>01.</span>
        Sélectionne tes jours d'entrainement.
    </h3>

    <div id="days">

        <label for="Lundi">Lundi</label>
        <input type="checkbox" id="monday" name="Lundi" hidden>

        <label for="Mardi">Mardi</label>
        <input type="checkbox" id="tuesday" name="Mardi" hidden>

        <label for="Mercredi">Mercredi</label>
        <input type="checkbox" id="wednesday" name="Mercredi" hidden>

        <label for="Jeudi">Jeudi</label>
        <input type="checkbox" id="thursday" name="Jeudi" hidden>

        <label for="Vendredi">Vendredi</label>
        <input type="checkbox" id="friday" name="Vendredi" hidden>

        <label for="Samedi">Samedi</label>
        <input type="checkbox" id="saturday" name="Samedi" hidden>

        <label for="Dimanche">Dimanche</label>
        <input type="checkbox" id="sunday" name="Dimanche" hidden>


    </div>

</section>

<section id="sessions-container">

    <h3 class="h3-titles">
        <span>02.</span>
        Inscris tes exercices.
    </h3>

    <form action="" method="POST" id="form-sessions">

        <div id="sessions">

        </div>

        <h3 class="h3-titles">
            <span>03.</span>
            Enregistre tes séances.
        </h3>

        <button type="submit" class="gymnotes-btn">C'est parti !</button>

    </form>

</section>
