

<!-- TYPEWRITER -->
<section id="section-1-homepage">

    <h1>GymNotes</h1>

    <div id="typewriter-container">

        <div class="typewriter">

            <div class="session-container">

                <h2 id="create-session" class="typewrited"></h2>

                <p> Inscris tes exercices, tes performances et tes temps de repos </p>

            </div>

            <div class="step-number">
                <p>.01</p>
                <span></span>
            </div>

        </div>

        <div class="typewriter">

            <div class="session-container">

                <h2 id="start-session" class="typewrited"></h2>

                <p> Suis ta routine à la lettre </p>

            </div>

            <div class="step-number">
                <p>.02</p>
                <span></span>
            </div>

        </div>

        <div class="typewriter">

            <div class="session-container">

                <h2 id="track-progress" class="typewrited"></h2>

                <p> Compare tes performances et ton évolution chaque semaine </p>

            </div>

            <div class="step-number">
                <p>.03</p>
                <span></span>
            </div>

        </div>

    </div>

    <a href="<?= url('/session') ?>" class="gymnotes-btn">Je me lance !</a>

</section>

<!-- WHAT IS GYMNOTES -->
<section id="section-2-homepage">

    <div id="what-is-gymnotes">
        <h3>Qu'est-ce que <span class="gymnotes">Gymnotes ?</span></h3>
        <h4>Un moyen d'organiser ses séances</h4>
        <p>Inscris tes séances hebdomadaires avec tes exercices, le nombre de séries, tes performances et tes temps de repos.</p>
        <h4>Fini de se perdre !</h4>
        <p>Une fois que tout est inscrit, tu n'as plus qu'à lancer ta séance du jour et suivre les indications !</p>
        <a href="<?= url('/session') ?>" class="gymnotes-btn">J'essaie !</a>
    </div>

    <div id="phone-container">
        <img src="../public/assets/img/iphone-placeholder.png" class="phone" alt="smartphone-showing-gymnotes-app">
    </div>

    <!-- <img src="../public/assets/img/blue-glow.png" class="glow" alt=""> -->

</section>

<!-- TRACK PROGRESS -->
<section id="section-3-homepage">
    <h3>Suis ta progression au fil des jours et reste <span>motivé !</span></h3>

    <div id="cards-homepage">
        <div id="cards-images">
            <ul>

                <li>
                    <img src="../public/assets/img/cards/alim.jpg" alt="">
                </li>

                <li>
                    <img src="../public/assets/img/cards/bicycle.jpg" alt="">
                </li>

                <li>
                    <img src="../public/assets/img/cards/alim.jpg" alt="">
                </li>

                <li>
                    <img src="../public/assets/img/cards/bicycle.jpg" alt="">
                </li>

                <li>
                    <img src="../public/assets/img/cards/alim.jpg" alt="">
                </li>

            </ul>
        </div>

        <div id="cards-title">

            <div id="titles">

                <ul>
                    <li>Running</li>
                    <li>Alimentation</li>
                    <li>Performances</li>
                    <li>Statistiques</li>
                    <li>Santé</li>
                </ul>

                <div>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

            </div>

            <a href="<?= url('/tracker') ?>" class="gymnotes-btn">JE TRACK MA PROGRESSION</a>

        </div>
    </div>

</section>

<!-- BEGINNER ? -->
<section id="section-4-homepage">
    <h3>DÉBUTANT ?</h3>

    <div id="offers-container">
        <div>
            <h4>
                Nos experts t'accompagnent pour 49€/mois !
            </h4>

            <p>
                On peut rapidement se perdre avec la tonne de documentation sur internet. Il est très difficile de composer avec et de différencier les bons des mauvais conseils.
            </p>

            <a href="<?= url('/free-month') ?>">JE DÉMARRE MON MOIS D'ESSAI GRATUIT</a>
        </div>

        <div>
            <h4>
                Une équipe de coachs et de médecins à ta disposition
            </h4>

            <p>
                Nous avons formé une équipe de passionnés les plus assidus dans leurs domaines pour optimiser et accélérer ta progression, peu importe tes objectifs.
            </p>

            <a href="<?= url('/team') ?>">JE DÉCOUVRE L'ÉQUIPE</a>
        </div>

    </div>

</section>

<!-- FREE TRAINING -->
<section id="free-content">
    <div id="preconceived">
        <h3>Nos programmes préconçus <span>GRATUITS !</span></h3>
        <p>Nous proposons également des programmes sportifs préconçus, adaptés en fonction de ta condition et de ton objectif que l'on détermine à travers notre questionnaire.</p>
        <p>ET TOUT ÇA, TOTALEMENT GRATUITEMENT !</p>
    </div>
    <div id="do-the-test">
        <a href="<?= url('/interview') ?>">FAIRE LE TEST</a>
    </div>
</section>

<!-- LAST ARTICLES -->
<section id="last-articles">

    <h3>Nos derniers <span>articles</span></h3>

    <div id="slider-container">

        <div class="slides">

            <div class="slide">

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

            </div>

            <div class="slide">

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

            </div>

            <div class="slide">

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

                <div>
                    <img src="../public/assets/img/background-interview.png" alt="">
                </div>

            </div>

        </div>

        <div class="circles">
            <span></span>
            <span></span>
            <span></span>
        </div>


        <button id="button-left"> < </button>

        <button id="button-right"> > </button>


    </div>
</section>