<section id="interview">

<?php if (isset($_SESSION['user_id'])) : ?>

        <h2>Mon programme personnalisé</h2>

        <form method="POST">

            <ul id="slider-interview">

                <li>

                    <h3>Je suis :</h3>

                    <div class="questions">

                        <label for="gender">Un homme</label>
                        <input type="radio" id="male" name="gender" value="homme" hidden>

                        <label for="gender">Une femme</label>
                        <input type="radio" id="female" name="gender" value="femme" hidden>

                    </div>

                    </div>

                </li>

                <li>

                    <h3>J'ai entre:</h3>

                    <div class="questions">

                        <label for="age">18 et 25 ans</label>
                        <input type="radio" id="18-25-years" name="age" value="18" hidden>


                        <label for="age">26 et 35 ans</label>
                        <input type="radio" id="26-35-years" name="age" value="26" hidden>


                        <label for="age">36 et 49 ans</label>
                        <input type="radio" id="36-50-years" name="age" value="36" hidden>


                        <label for="age">+ de 50 ans</label>
                        <input type="radio" id="50-more-years" name="age" value="50" hidden>


                    </div>

                </li>

                <li>

                    <h3>Je souhaite pratiquer du sport :</h3>

                    <div class="questions">

                        <label for="sessionPerWeek">1 fois par semaine</label>
                        <input type="radio" id="once" name="sessionPerWeek" value="1" hidden>

                        <label for="sessionPerWeek">2 fois par semaine</label>
                        <input type="radio" id="twice" name="sessionPerWeek" value="2" hidden>

                        <label for="sessionPerWeek">3 fois par semaine</label>
                        <input type="radio" id="thrice" name="sessionPerWeek" value="3" hidden>

                        <label for="sessionPerWeek">4 fois par semaine</label>
                        <input type="radio" id="four" name="sessionPerWeek" value="4" hidden>

                        <label for="sessionPerWeek">5 fois par semaine ou plus</label>
                        <input type="radio" id="five" name="sessionPerWeek" value="5" hidden>

                    </div>

                </li>

                <li>

                    <h3>Je pèse :</h3>

                    <div class="questions">

                        <label for="weight">Entre 41 et 55 kilos</label>
                        <input type="radio" id="41-55-kilos" name="weight" value="55" hidden>

                        <label for="weight">Entre 56 et 70 kilos</label>
                        <input type="radio" id="56-70-kilos" name="weight" value="70" hidden>

                        <label for="weight">Entre 71 et 85 kilos</label>
                        <input type="radio" id="71-85-kilos" name="weight" value="85" hidden>

                        <label for="weight">Entre 86 et 99 kilos</label>
                        <input type="radio" id="86-99-kilos" name="weight" value="99" hidden>

                        <label for="weight">+ de 100 kilos</label>
                        <input type="radio" id="100-more-kilos" name="weight" value="100" hidden>

                    </div>

                </li>

            </ul>

            <div class="buttons">

                <button type="button" id="buttonValid">Valider</button>

            </div>

        </form>


<?php else : ?>
    <h2>Veuillez vous connecter pour accéder à cette fonctionalité.</h2>
    <?php require 'userform.phtml' ?>
<?php endif; ?>

</section>