

<section id="start-or-create">

    <?php if (isset($_SESSION['user_id'])) : ?>
    <div id="buttons-session-container">
            <a class="gymnotes-btn" href="<?= url('/start-session') ?>">J'ai déjà ma séance de prête</a>
            <a class="gymnotes-btn" href="<?= url('/create-session') ?>">Je crée mes séances</a>
    </div>

    <?php else : ?>

    <p class="require-log">Veuillez vous connecter pour accéder à cette fonctionnalité.</h3>
        <?php require 'userform.phtml' ?>

    <?php endif; ?>

</section>