<div>

    <div id="login">

        <p>Se connecter</p>

        <form action="" method="post">

            <label for="mail">Votre adresse mail</label>
            <input type="text" name="mail">

            <label for="password">Votre mot de passe</label>
            <input type="password" name="password">

        </form>

        <button type="submit">Se connecter</button>

    </div>

    <div id="register">

        <p>Pas encore inscrit ?</p>

        <form action="" method="post">

            <label for="lastname">Nom</label>
            <input type="text" name="lastname" placeholder="Votre nom" required>

            <label for="firstname">Prénom</label>
            <input type="text" name="firstname" placeholder="Votre prénom" required>

            <label for="mail">Adresse mail</label>
            <input type="text" name="mail" required>

            <select name="gender" required>
                <option value="male">Homme</option>
                <option value="female">Femme</option>
            </select>

            <select name="age" id="age" required>

            </select>

            <label for="password">Votre mot de passe</label>
            <input type="password" name="password" required>

        </form>

        <button type="submit">S'inscrire</button>

    </div>

</div>