<div id="login-register">

    <div id="login">

        <p>Se connecter</p>

        <form method="post">

            <input type="text" name="mail-login" placeholder="Votre mail" required>

            <?php if (isset($_SESSION['wrong-id'])) : ?>
                    <p class="error-form">Ce mail n'existe pas ou les identifiants sont incorrects.</p>
                    <?php unset($_SESSION['wrong-id']) ?>
                <?php endif; ?>

            <input type="password" name="password-login" placeholder="Votre mot de passe" required>

            <button type="submit">Se connecter</button>

        </form>



    </div>

    <div id="register">

        <p>Pas encore inscrit ?</p>

        <form method="post">

            <input type="text" name="lastname" placeholder="Votre nom" required>

                <?php if (isset($_SESSION['lastname'])) : ?>
                    <p class="error-form">Veuillez entrer un nom valide.</p>
                    <?php unset($_SESSION['lastname']) ?>
                <?php endif; ?>

            <input type="text" name="firstname" placeholder="Votre prénom" required>

                <?php if (isset($_SESSION['firstname'])) : ?>
                    <p class="error-form">Veuillez entrer un prénom valide.</p>
                    <?php unset($_SESSION['firstname']) ?>
                <?php endif; ?>

            <input type="text" name="mail" placeholder="Votre mail" required>

                <?php if (isset($_SESSION['mail'])) : ?>
                    <p class="error-form">Veuillez entrer un mail valide.</p>
                    <?php unset($_SESSION['mail']) ?>
                <?php endif; ?>

            <select name="gender" required>
                <option selected disabled>Sélectionnez votre genre</option>
                <option value="male">Homme</option>
                <option value="female">Femme</option>
            </select>

                <?php if (isset($_SESSION['gender-null'])) : ?>
                    <p class="error-form">Veuillez sélectionner votre genre.</p>
                    <?php unset($_SESSION['gender-null']) ?>
                <?php endif; ?>

            <select name="age" id="age" required>
                <option selected disabled>Sélectionnez votre âge</option>
            </select>

                <?php if (isset($_SESSION['age-null'])) : ?>
                    <p class="error-form">Veuillez sélectionner votre âge.</p>
                    <?php unset($_SESSION['age-null']) ?>
                <?php endif; ?>

            <input type="password" name="password" placeholder="Votre mot de passe" required>

                <?php if (isset($_SESSION['password-short'])) : ?>
                    <p class="error-form">Votre mot de passe doit contenir un minimum de 8 caractères.</p>
                    <?php unset($_SESSION['password-short']) ?>
                <?php endif; ?>

            <button type="submit">S'inscrire</button>

        </form>

    </div>

</div>